### ISSUE TITLE
Visualize bivariate histogram with percentiles

### ISSUE THREAD

**Issue by joseribasfernandes** [iVibudh/cer-esa-indigenous-knowledge#1]
Set percentiles to 0.25, 0.5, 0.75

**Comment by joseribasfernandes** [comment]
https://seaborn.pydata.org/tutorial/distributions.html

try three levels:
sns.displot(penguins, x="bill_length_mm", y="bill_depth_mm", kind="kde", levels=[.25, .5, .75])

**Comment by iVibudh** [comment]
Ref -> https://seaborn.pydata.org/tutorial/distributions.html

**Comment by joseribasfernandes** [comment]
![image](https://user-images.githubusercontent.com/57156394/151248062-f5402582-9225-43ce-849c-e567bd01bae5.png)

**Comment by iVibudh** [comment]
Done.
![image](https://user-images.githubusercontent.com/33818829/152025527-cc2f84cc-d692-497f-a819-58a12d7bf12a.png)

**Comment by iVibudh** [comment]
Done
